import { NextRequest, NextResponse } from 'next/server'
import { extractVideoId } from '@/lib/utils'

export interface LanguageInfo {
  languageCode: string
  languageName: string
  isAutoGenerated: boolean
}

export interface LanguagesResponse {
  videoId: string
  languages: LanguageInfo[]
  totalLanguages: number
}

export interface LanguagesError {
  error: string
}

// Language code to name mapping
const LANGUAGE_NAMES: Record<string, string> = {
  en: 'English',
  th: 'Thai',
  es: 'Spanish',
  fr: 'French',
  de: 'German',
  ja: 'Japanese',
  ko: 'Korean',
  zh: 'Chinese',
  'zh-Hans': 'Chinese (Simplified)',
  'zh-Hant': 'Chinese (Traditional)',
  pt: 'Portuguese',
  it: 'Italian',
  ru: 'Russian',
  ar: 'Arabic',
  hi: 'Hindi',
  vi: 'Vietnamese',
  id: 'Indonesian',
  nl: 'Dutch',
  pl: 'Polish',
  tr: 'Turkish',
  sv: 'Swedish',
  da: 'Danish',
  fi: 'Finnish',
  no: 'Norwegian',
  cs: 'Czech',
  hu: 'Hungarian',
  ro: 'Romanian',
  uk: 'Ukrainian',
  el: 'Greek',
  he: 'Hebrew',
  ca: 'Catalan',
  bg: 'Bulgarian',
  hr: 'Croatian',
  sr: 'Serbian',
  sk: 'Slovak',
  sl: 'Slovenian',
  et: 'Estonian',
  lv: 'Latvian',
  lt: 'Lithuanian',
  mt: 'Maltese',
  ga: 'Irish',
  cy: 'Welsh',
  // Add more as needed
}

function getLanguageName(code: string): string {
  return LANGUAGE_NAMES[code] || code.toUpperCase()
}

export async function GET(request: NextRequest) {
  try {
    const searchParams = request.nextUrl.searchParams
    const videoId = searchParams.get('videoId')

    // Validate videoId
    if (!videoId) {
      return NextResponse.json<LanguagesError>(
        { error: 'Video ID is required' },
        { status: 400 }
      )
    }

    // Validate video ID format (should be 11 characters)
    if (videoId.length !== 11) {
      return NextResponse.json<LanguagesError>(
        { error: 'Invalid YouTube video ID' },
        { status: 400 }
      )
    }

    try {
      // Use YouTube Data API v3 to fetch available captions
      const apiKey = process.env.YOUTUBE_API_KEY

      if (!apiKey) {
        // Fallback: Try to fetch from YouTube page directly
        return await fetchLanguagesFromPage(videoId)
      }

      const apiUrl = `https://www.googleapis.com/youtube/v3/captions?part=snippet&videoId=${videoId}&key=${apiKey}`

      const response = await fetch(apiUrl)

      if (!response.ok) {
        // If API fails, try fallback method
        return await fetchLanguagesFromPage(videoId)
      }

      const data = await response.json()

      if (!data.items || data.items.length === 0) {
        // If API returns no items, try fallback method
        return await fetchLanguagesFromPage(videoId)
      }

      // Transform API response
      const languages: LanguageInfo[] = data.items.map((item: any) => ({
        languageCode: item.snippet.language,
        languageName: getLanguageName(item.snippet.language),
        isAutoGenerated: item.snippet.trackKind === 'ASR',
      }))

      // Remove duplicates and sort
      const uniqueLanguages = languages.filter(
        (lang, index, self) =>
          index === self.findIndex((l) => l.languageCode === lang.languageCode)
      )

      uniqueLanguages.sort((a, b) => a.languageName.localeCompare(b.languageName))

      const result: LanguagesResponse = {
        videoId,
        languages: uniqueLanguages,
        totalLanguages: uniqueLanguages.length,
      }

      return NextResponse.json(result, { status: 200 })
    } catch (error: any) {
      console.error('Error fetching languages:', error)

      // Try fallback method
      try {
        return await fetchLanguagesFromPage(videoId)
      } catch (fallbackError) {
        return NextResponse.json<LanguagesError>(
          {
            error: 'Unable to fetch available languages. Please try again later.',
          },
          { status: 500 }
        )
      }
    }
  } catch (error) {
    return NextResponse.json<LanguagesError>(
      {
        error: 'An error occurred while processing your request',
      },
      { status: 500 }
    )
  }
}

// Fallback method: Fetch from YouTube page directly
async function fetchLanguagesFromPage(videoId: string): Promise<NextResponse> {
  try {
    // Fetch YouTube watch page
    const watchUrl = `https://www.youtube.com/watch?v=${videoId}`
    const response = await fetch(watchUrl, {
      headers: {
        'User-Agent':
          'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
      },
    })

    if (!response.ok) {
      throw new Error('Failed to fetch YouTube page')
    }

    const html = await response.text()

    // Extract caption tracks from page HTML
    // YouTube stores caption tracks in a JSON object in the page
    const captionTracksMatch = html.match(
      /"captionTracks":(\[[^\]]*\])/
    )

    if (captionTracksMatch) {
      try {
        const captionTracks = JSON.parse(captionTracksMatch[1])
        const languages: LanguageInfo[] = captionTracks.map((track: any) => ({
          languageCode: track.languageCode,
          languageName: track.name?.simpleText || getLanguageName(track.languageCode),
          isAutoGenerated: track.kind === 'asr',
        }))

        return NextResponse.json<LanguagesResponse>(
          {
            videoId,
            languages,
            totalLanguages: languages.length,
          },
          { status: 200 }
        )
      } catch (parseError) {
        console.error('Failed to parse caption tracks:', parseError)
      }
    }

    // If we can't extract from page, return common languages
    const commonLanguages = ['en', 'th', 'es', 'fr', 'de', 'ja', 'ko', 'zh']
    const languages: LanguageInfo[] = commonLanguages.map((code) => ({
      languageCode: code,
      languageName: getLanguageName(code),
      isAutoGenerated: false,
    }))

    return NextResponse.json<LanguagesResponse>(
      {
        videoId,
        languages,
        totalLanguages: languages.length,
      },
      { status: 200 }
    )
  } catch (error) {
    console.error('Error fetching languages from page:', error)

    // Return common languages as fallback
    const commonLanguages = ['en', 'th', 'es', 'fr', 'de', 'ja', 'ko', 'zh']
    const languages: LanguageInfo[] = commonLanguages.map((code) => ({
      languageCode: code,
      languageName: getLanguageName(code),
      isAutoGenerated: false,
    }))

    return NextResponse.json<LanguagesResponse>(
      {
        videoId,
        languages,
        totalLanguages: languages.length,
      },
      { status: 200 }
    )
  }
}

