'use client'

import { useState, useRef, useEffect } from 'react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import {
  Copy,
  Download,
  Loader2,
  Moon,
  Sun,
  FileText,
  AlertCircle,
  Youtube,
  Languages,
  RefreshCw,
} from 'lucide-react'
import { extractVideoId, isValidYouTubeUrl } from '@/lib/utils'
import {
  formatAsText,
  formatAsSRT,
  formatAsJSON,
  getFileExtension,
} from '@/lib/format'
import { TranscriptItem, FormatType, SUPPORTED_LANGUAGES } from '@/lib/types'

type AppState = 'empty' | 'loading' | 'success' | 'error'

interface AvailableLanguage {
  languageCode: string
  languageName: string
  isAutoGenerated: boolean
}

export default function Home() {
  const [url, setUrl] = useState('')
  const [videoId, setVideoId] = useState<string | null>(null)
  const [transcript, setTranscript] = useState<TranscriptItem[]>([])
  const [state, setState] = useState<AppState>('empty')
  const [error, setError] = useState<string>('')
  const [language, setLanguage] = useState('en')
  const [format, setFormat] = useState<FormatType>('text')
  const [darkMode, setDarkMode] = useState(false)
  const [availableLanguages, setAvailableLanguages] = useState<AvailableLanguage[]>([])
  const [loadingLanguages, setLoadingLanguages] = useState(false)
  const [hasAutoDownloaded, setHasAutoDownloaded] = useState(false)
  const textareaRef = useRef<HTMLTextAreaElement>(null)

  // Handle dark mode
  useEffect(() => {
    const isDark = localStorage.getItem('darkMode') === 'true'
    setDarkMode(isDark)
    if (isDark) {
      document.documentElement.classList.add('dark')
    }
  }, [])

  const toggleDarkMode = () => {
    const newDarkMode = !darkMode
    setDarkMode(newDarkMode)
    localStorage.setItem('darkMode', String(newDarkMode))
    if (newDarkMode) {
      document.documentElement.classList.add('dark')
    } else {
      document.documentElement.classList.remove('dark')
    }
  }

  // Scroll to top when transcript is loaded
  useEffect(() => {
    if (state === 'success' && textareaRef.current) {
      textareaRef.current.scrollTop = 0
    }
  }, [state, transcript])

  // Auto-download when transcript is successfully fetched (only once per video)
  useEffect(() => {
    if (state === 'success' && transcript.length > 0 && !hasAutoDownloaded) {
      // Log transcript to console
      console.log('✅ Transcript loaded successfully!')
      console.log('📊 Transcript Info:', {
        videoId,
        language,
        format,
        totalSegments: transcript.length,
        totalDuration: transcript.reduce((sum, item) => sum + item.duration, 0).toFixed(2) + 's',
      })
      console.log('📝 Full Transcript (Text Format):', formatAsText(transcript))
      console.log('📄 Full Transcript Data:', transcript)
      
      // Delay download slightly to let user see the transcript first
      const timer = setTimeout(() => {
        handleDownload()
        setHasAutoDownloaded(true)
        console.log('💾 Auto-download completed!')
      }, 1500) // 1.5 second delay

      return () => clearTimeout(timer)
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [state, transcript, hasAutoDownloaded])

  // Track if we should auto-fetch transcript after language selection
  const [shouldAutoFetch, setShouldAutoFetch] = useState(false)

  // Fetch transcript when language changes (only if auto-fetch is enabled)
  useEffect(() => {
    if (shouldAutoFetch && videoId && availableLanguages.length > 0 && language && state !== 'loading') {
      setShouldAutoFetch(false) // Reset flag
      fetchTranscriptForVideoId(videoId)
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [language, videoId, availableLanguages.length, shouldAutoFetch])

  const fetchTranscriptForVideoId = async (id: string) => {
    setState('loading')
    setError('')

    try {
      const response = await fetch(
        `/api/transcript?videoId=${id}&lang=${language}`
      )

      if (!response.ok) {
        const errorData = await response.json()
        throw new Error(errorData.error || 'Failed to fetch transcript')
      }

      const data = await response.json()
      setTranscript(data.transcript)
      setState('success')
      
      // Log transcript to console
      console.log('📝 Transcript fetched successfully!')
      console.log('Video ID:', id)
      console.log('Language:', language)
      console.log('Total segments:', data.transcript.length)
      console.log('--- Transcript Content ---')
      
      // Log formatted transcript based on current format
      const formattedText = formatAsText(data.transcript)
      console.log('Text format:', formattedText)
      console.log('--- Full Transcript Data ---')
      console.log(data.transcript)
    } catch (err: any) {
      setError(err.message || 'An error occurred while fetching the transcript')
      setState('error')
      setTranscript([])
    }
  }

  const fetchAvailableLanguages = async (id: string) => {
    setLoadingLanguages(true)
    // Don't set state to 'loading' here - keep it as is so select shows
    try {
      const response = await fetch(`/api/languages?videoId=${id}`)
      if (response.ok) {
        const data = await response.json()
        const languages = data.languages || []
        
        // Remove duplicates by languageCode
        const uniqueLanguages = languages.filter(
          (lang: AvailableLanguage, index: number, self: AvailableLanguage[]) =>
            index === self.findIndex((l) => l.languageCode === lang.languageCode)
        )
        
        setAvailableLanguages(uniqueLanguages)
        
        // Auto-select first available language if current language is not available
        if (uniqueLanguages.length > 0) {
          const currentLangAvailable = uniqueLanguages.some(
            (lang: AvailableLanguage) => lang.languageCode === language
          )
          if (!currentLangAvailable) {
            // Auto-select first language
            setLanguage(uniqueLanguages[0].languageCode)
          }
          // Don't auto-fetch transcript - let user select language first
          setState('empty')
        } else {
          setState('error')
          setError('No languages available for this video')
        }
      } else {
        setState('error')
        setError('Failed to fetch available languages')
      }
    } catch (err) {
      console.error('Failed to fetch available languages:', err)
      setState('error')
      setError('Failed to fetch available languages')
      setAvailableLanguages([])
    } finally {
      setLoadingLanguages(false)
    }
  }

  const handleFetchTranscript = async () => {
    // Validate URL
    if (!url.trim()) {
      setError('Please enter a YouTube URL')
      setState('error')
      return
    }

    const extractedVideoId = extractVideoId(url)
    if (!extractedVideoId) {
      setError('Invalid YouTube URL. Please enter a valid URL.')
      setState('error')
      return
    }

    // Reset auto-download flag when fetching new video
    if (videoId !== extractedVideoId) {
      setHasAutoDownloaded(false)
      setTranscript([]) // Clear previous transcript
      setState('empty') // Reset to empty state
      setAvailableLanguages([]) // Clear previous languages
    }

    setVideoId(extractedVideoId)
    
    // Fetch available languages first (don't fetch transcript yet)
    await fetchAvailableLanguages(extractedVideoId)
    
    // Don't auto-fetch transcript - user will select language and click "Get Transcript" again
  }

  // Handle manual transcript fetch after language selection
  const handleGetTranscript = () => {
    if (!videoId) return
    setShouldAutoFetch(true) // Enable auto-fetch flag
    fetchTranscriptForVideoId(videoId)
  }

  const handleCopy = async () => {
    if (!transcript.length) return

    let text = ''
    switch (format) {
      case 'text':
        text = formatAsText(transcript)
        break
      case 'srt':
        text = formatAsSRT(transcript)
        break
      case 'json':
        text = formatAsJSON(transcript)
        break
    }

    try {
      await navigator.clipboard.writeText(text)
      // You could add a toast notification here
    } catch (err) {
      console.error('Failed to copy:', err)
    }
  }

  const handleDownload = () => {
    if (!transcript.length) return

    let content = ''
    switch (format) {
      case 'text':
        content = formatAsText(transcript)
        break
      case 'srt':
        content = formatAsSRT(transcript)
        break
      case 'json':
        content = formatAsJSON(transcript)
        break
    }

    const blob = new Blob([content], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `transcript-${videoId || 'video'}.${getFileExtension(format)}`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  const getFormattedTranscript = (): string => {
    if (!transcript.length) return ''

    switch (format) {
      case 'text':
        return formatAsText(transcript)
      case 'srt':
        return formatAsSRT(transcript)
      case 'json':
        return formatAsJSON(transcript)
      default:
        return formatAsText(transcript)
    }
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-50 to-gray-100 dark:from-gray-900 dark:to-gray-800 transition-colors">
      {/* Header */}
      <header className="sticky top-0 z-50 w-full border-b bg-white/80 dark:bg-gray-900/80 backdrop-blur-sm">
        <div className="container mx-auto px-4 py-4 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Youtube className="h-6 w-6 text-red-600" />
            <h1 className="text-xl font-bold bg-gradient-to-r from-blue-600 to-purple-600 bg-clip-text text-transparent">
              YouTube Transcript
            </h1>
          </div>
          <Button
            variant="ghost"
            size="icon"
            onClick={toggleDarkMode}
            aria-label="Toggle dark mode"
          >
            {darkMode ? (
              <Sun className="h-5 w-5" />
            ) : (
              <Moon className="h-5 w-5" />
            )}
          </Button>
        </div>
      </header>

      {/* Main Content */}
      <main className="container mx-auto px-4 py-8 max-w-4xl">
        {/* Hero Section */}
        <div className="text-center mb-8 space-y-4">
          <h2 className="text-4xl md:text-5xl font-bold bg-gradient-to-r from-blue-600 to-purple-600 bg-clip-text text-transparent">
            Get YouTube Video Transcripts
          </h2>
          <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
            Extract subtitles and transcripts from YouTube videos instantly.
            Support multiple languages and export formats.
          </p>
        </div>

        {/* URL Input Section */}
        <Card className="mb-6 shadow-lg">
          <CardContent className="pt-6">
            <div className="flex flex-col sm:flex-row gap-4">
              <div className="flex-1 relative">
                <Input
                  type="text"
                  placeholder="Paste YouTube URL here (e.g., https://www.youtube.com/watch?v=...)"
                  value={url}
                  onChange={(e) => setUrl(e.target.value)}
                  onKeyDown={(e) => {
                    if (e.key === 'Enter') {
                      handleFetchTranscript()
                    }
                  }}
                  className="h-14 text-base pr-32"
                  disabled={state === 'loading'}
                />
                <Button
                  onClick={handleFetchTranscript}
                  disabled={state === 'loading' || !url.trim()}
                  className="absolute right-2 top-2 h-10 bg-gradient-to-r from-blue-600 to-purple-600 hover:from-blue-700 hover:to-purple-700"
                >
                  {state === 'loading' ? (
                    <>
                      <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                      Loading...
                    </>
                  ) : (
                    'Get Transcript'
                  )}
                </Button>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Options Bar - Always show when videoId exists */}
        {videoId && (
          <Card className="mb-6 shadow-lg">
            <CardContent className="pt-6">
              <div className="flex flex-col sm:flex-row gap-4">
                <div className="flex-1">
                  <div className="flex items-center justify-between mb-2">
                    <label className="text-sm font-medium">
                      Language
                    </label>
                    {loadingLanguages ? (
                      <div className="flex items-center gap-2 text-xs text-muted-foreground">
                        <Loader2 className="h-3 w-3 animate-spin" />
                        <span>Loading languages...</span>
                      </div>
                    ) : availableLanguages.length > 0 ? (
                      <div className="flex items-center gap-2 text-xs text-muted-foreground">
                        <Languages className="h-3 w-3" />
                        <span>{availableLanguages.length} available</span>
                      </div>
                    ) : null}
                  </div>
                  <Select
                    value={language}
                    onValueChange={setLanguage}
                    disabled={state === 'loading' || loadingLanguages}
                  >
                    <SelectTrigger>
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      {availableLanguages.length > 0 ? (
                        // Show only available languages (already deduplicated)
                        availableLanguages.map((lang, index) => (
                          <SelectItem
                            key={`${lang.languageCode}-${index}`}
                            value={lang.languageCode}
                          >
                            <div className="flex items-center gap-2">
                              <span>{lang.languageName}</span>
                              {lang.isAutoGenerated && (
                                <span className="text-xs text-muted-foreground">
                                  (Auto)
                                </span>
                              )}
                            </div>
                          </SelectItem>
                        ))
                      ) : (
                        // Fallback to supported languages if available languages not loaded
                        SUPPORTED_LANGUAGES.map((lang) => (
                          <SelectItem key={lang.value} value={lang.value}>
                            {lang.label}
                          </SelectItem>
                        ))
                      )}
                    </SelectContent>
                  </Select>
                  {availableLanguages.length > 0 && (
                    <button
                      onClick={() => videoId && fetchAvailableLanguages(videoId)}
                      disabled={loadingLanguages}
                      className="mt-2 text-xs text-muted-foreground hover:text-foreground flex items-center gap-1 transition-colors"
                    >
                      <RefreshCw
                        className={`h-3 w-3 ${loadingLanguages ? 'animate-spin' : ''}`}
                      />
                      Refresh languages
                    </button>
                  )}
                </div>
                <div className="flex-1">
                  <label className="text-sm font-medium mb-2 block">
                    Format
                  </label>
                  <Tabs value={format} onValueChange={(v) => setFormat(v as FormatType)}>
                    <TabsList className="w-full">
                      <TabsTrigger value="text" className="flex-1">
                        Text
                      </TabsTrigger>
                      <TabsTrigger value="srt" className="flex-1">
                        SRT
                      </TabsTrigger>
                      <TabsTrigger value="json" className="flex-1">
                        JSON
                      </TabsTrigger>
                    </TabsList>
                  </Tabs>
                  <p className="text-xs text-muted-foreground mt-2">
                    {format === 'text' && 'Plain text format - all segments joined together'}
                    {format === 'srt' && 'SubRip subtitle format with timestamps'}
                    {format === 'json' && 'Raw JSON data with text, duration, and offset'}
                  </p>
                </div>
              </div>
              {/* Get Transcript Button - Show when languages are loaded */}
              {availableLanguages.length > 0 && (
                <div className="mt-4 flex justify-end">
                  <Button
                    onClick={handleGetTranscript}
                    disabled={state === 'loading' || !language}
                    className="bg-gradient-to-r from-blue-600 to-purple-600 hover:from-blue-700 hover:to-purple-700"
                  >
                    {state === 'loading' ? (
                      <>
                        <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                        Loading transcript...
                      </>
                    ) : (
                      'Get Transcript'
                    )}
                  </Button>
                </div>
              )}
            </CardContent>
          </Card>
        )}

        {/* Result Area */}
        {state === 'loading' && (
          <Card className="shadow-lg">
            <CardContent className="pt-6">
              <div className="flex flex-col items-center justify-center py-12">
                <Loader2 className="h-12 w-12 animate-spin text-blue-600 mb-4" />
                <p className="text-lg text-muted-foreground">
                  Loading transcript...
                </p>
              </div>
            </CardContent>
          </Card>
        )}

        {state === 'error' && (
          <Card className="shadow-lg border-destructive">
            <CardContent className="pt-6">
              <div className="flex items-start gap-4">
                <AlertCircle className="h-5 w-5 text-destructive mt-0.5" />
                <div className="flex-1">
                  <h3 className="font-semibold text-destructive mb-2">
                    Error
                  </h3>
                  <div className="text-muted-foreground whitespace-pre-line">
                    {error}
                  </div>
                  {availableLanguages.length > 0 && (
                    <div className="mt-4 p-3 bg-blue-50 dark:bg-blue-900/20 rounded-md">
                      <p className="text-sm text-blue-900 dark:text-blue-200 font-medium mb-1">
                        💡 Tip: Found {availableLanguages.length} languages but cannot fetch transcript.
                      </p>
                      <p className="text-xs text-blue-700 dark:text-blue-300">
                        This usually means the video doesn&apos;t have transcript in the selected language. Try selecting a different language or a different video.
                      </p>
                    </div>
                  )}
                </div>
              </div>
            </CardContent>
          </Card>
        )}

        {state === 'empty' && (
          <Card className="shadow-lg">
            <CardContent className="pt-6">
              <div className="flex flex-col items-center justify-center py-12 text-center">
                <FileText className="h-16 w-16 text-muted-foreground mb-4" />
                <h3 className="text-xl font-semibold mb-2">
                  No transcript yet
                </h3>
                <p className="text-muted-foreground">
                  Paste a YouTube URL above to get started
                </p>
              </div>
            </CardContent>
          </Card>
        )}

        {state === 'success' && transcript.length > 0 && (
          <Card className="shadow-lg">
            <CardHeader>
              <div className="flex items-center justify-between">
                <CardTitle>
                  Transcript ({transcript.length} segments)
                </CardTitle>
                <div className="flex gap-2">
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={handleCopy}
                    className="gap-2"
                  >
                    <Copy className="h-4 w-4" />
                    Copy
                  </Button>
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={handleDownload}
                    className={`gap-2 ${
                      hasAutoDownloaded
                        ? 'bg-green-50 dark:bg-green-900/20 border-green-200 dark:border-green-800 hover:bg-green-100 dark:hover:bg-green-900/30'
                        : ''
                    }`}
                  >
                    <Download className="h-4 w-4" />
                    {hasAutoDownloaded ? 'Download Again' : 'Download'}
                  </Button>
                </div>
              </div>
            </CardHeader>
            <CardContent>
              <Textarea
                ref={textareaRef}
                readOnly
                value={getFormattedTranscript()}
                className="min-h-[400px] font-mono text-sm"
                style={{
                  fontFamily:
                    format === 'srt' || format === 'json'
                      ? 'monospace'
                      : 'inherit',
                }}
              />
            </CardContent>
          </Card>
        )}

        {/* Footer */}
        <footer className="mt-12 text-center text-sm text-muted-foreground">
          <p>Made with ❤️ for easy YouTube transcript extraction</p>
        </footer>
      </main>
    </div>
  )
}

